# Generated by Django 6.0.4 on 2026-04-25 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('batch_number', models.CharField(help_text='Auto-generated unique batch identifier', max_length=50, unique=True, verbose_name='Batch Number')),
                ('arrival_date', models.DateTimeField(db_index=True, verbose_name='Arrival Date')),
                ('status', models.CharField(choices=[('pending', 'Pending / মুলতুবি'), ('confirmed', 'Confirmed / নিশ্চিত'), ('rejected', 'Rejected / প্রত্যাখ্যাত'), ('cancelled', 'Cancelled / বাতিল')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('source_location', models.CharField(blank=True, default='', max_length=200, verbose_name='Source Location')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_arrivals', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed By')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='drivers.driver', verbose_name='Driver')),
            ],
            options={
                'verbose_name': 'Arrival',
                'verbose_name_plural': 'Arrivals',
                'ordering': ['-arrival_date'],
            },
        ),
        migrations.CreateModel(
            name='ArrivalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantity')),
                ('unit_price_at_arrival', models.DecimalField(decimal_places=2, help_text='Snapshot of price at arrival time — product.unit_price is the live reference', max_digits=12, verbose_name='Unit Price at Arrival')),
                ('quality_grade', models.CharField(choices=[('A', 'Grade A — Premium'), ('B', 'Grade B — Standard'), ('C', 'Grade C — Below Standard'), ('D', 'Grade D — Damaged')], default='A', max_length=5, verbose_name='Quality Grade')),
                ('notes', models.TextField(blank=True, default='')),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='arrivals.arrival', verbose_name='Arrival')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_items', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Arrival Item',
                'verbose_name_plural': 'Arrival Items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='arrival',
            index=models.Index(fields=['status', 'arrival_date'], name='arrivals_ar_status_0234d2_idx'),
        ),
        migrations.AddIndex(
            model_name='arrival',
            index=models.Index(fields=['batch_number'], name='arrivals_ar_batch_n_f1be4c_idx'),
        ),
    ]
