# Generated by Django 6.0.4 on 2026-04-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('name_bn', models.CharField(blank=True, default='', max_length=200, verbose_name='নাম')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone Number')),
                ('alt_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Alternative Phone')),
                ('nid_number', models.CharField(blank=True, default='', max_length=20, verbose_name='NID Number')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='License Number')),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck / ট্রাক'), ('pickup', 'Pickup / পিকআপ'), ('van', 'Van / ভ্যান'), ('lorry', 'Lorry / লরি'), ('trailer', 'Trailer / ট্রেইলার'), ('three_wheeler', 'Three Wheeler / তিন চাকা'), ('other', 'Other / অন্যান্য')], default='truck', max_length=20, verbose_name='Vehicle Type')),
                ('vehicle_number', models.CharField(max_length=50, verbose_name='Vehicle Number')),
                ('address', models.TextField(blank=True, default='', verbose_name='Address')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/%Y/%m/')),
                ('is_available', models.BooleanField(db_index=True, default=True, verbose_name='Available')),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['phone'], name='drivers_dri_phone_39e97b_idx'), models.Index(fields=['license_number'], name='drivers_dri_license_ce5f7e_idx'), models.Index(fields=['is_available'], name='drivers_dri_is_avai_c3105f_idx')],
            },
        ),
    ]
