# Generated by Django 6.0.4 on 2026-04-25 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('manager', 'Warehouse Manager'), ('operator', 'Warehouse Operator'), ('viewer', 'Viewer (Read Only)')], default='operator', max_length=20, verbose_name='Role')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Phone')),
                ('designation', models.CharField(blank=True, default='', max_length=100, verbose_name='Designation')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/')),
                ('language_preference', models.CharField(choices=[('en', 'English'), ('bn', 'বাংলা')], default='en', max_length=5, verbose_name='Language')),
                ('receive_notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
