# Generated by Django 6.0.4 on 2026-04-25 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('arrival', 'Goods Arrival (Expense)'), ('dispatch', 'Goods Dispatch (Revenue)'), ('adjustment', 'Manual Adjustment'), ('refund', 'Refund')], db_index=True, max_length=20, verbose_name='Transaction Type')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price at time of transaction', max_digits=12, verbose_name='Unit Price')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total Amount')),
                ('transaction_date', models.DateTimeField(db_index=True, verbose_name='Transaction Date')),
                ('reference', models.CharField(blank=True, default='', help_text='e.g., Arrival batch or Pickup number', max_length=100, verbose_name='Reference')),
                ('notes', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_entries', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Revenue Entry',
                'verbose_name_plural': 'Revenue Entries',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['transaction_type', 'transaction_date'], name='revenue_rev_transac_8df37b_idx'), models.Index(fields=['product', 'transaction_date'], name='revenue_rev_product_5af5d4_idx')],
            },
        ),
    ]
