# Generated by Django 6.0.4 on 2026-04-25 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_type', models.CharField(choices=[('addition', 'Stock Addition'), ('removal', 'Stock Removal'), ('reservation', 'Stock Reserved'), ('release', 'Reservation Released'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('quantity_change', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantity_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantity_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source', models.CharField(blank=True, default='', help_text='Source reference (e.g., Arrival batch, Pickup number)', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Inventory Log',
                'verbose_name_plural': 'Inventory Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Quantity')),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity reserved for pending pickups', max_digits=14, verbose_name='Reserved Quantity')),
                ('warehouse_location', models.CharField(blank=True, default='', help_text='Physical location in warehouse (e.g., Section A, Rack 3)', max_length=100, verbose_name='Warehouse Location')),
                ('last_restock_date', models.DateTimeField(blank=True, null=True)),
                ('last_dispatch_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_record', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Inventory Record',
                'verbose_name_plural': 'Inventory Records',
                'ordering': ['product__name'],
                'indexes': [models.Index(fields=['total_quantity'], name='inventory_i_total_q_80ab75_idx')],
            },
        ),
    ]
