# Generated by Django 6.0.4 on 2026-04-25 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(db_index=True, verbose_name='Year')),
                ('month', models.PositiveIntegerField(db_index=True, verbose_name='Month')),
                ('total_arrived', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Arrived')),
                ('total_dispatched', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Dispatched')),
                ('total_arrival_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Arrival Value')),
                ('total_dispatch_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Dispatch Value')),
                ('opening_stock', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Opening Stock')),
                ('closing_stock', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Closing Stock')),
                ('avg_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Avg Unit Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Monthly Report',
                'verbose_name_plural': 'Monthly Reports',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['year', 'month'], name='reports_mon_year_1c66f3_idx'), models.Index(fields=['product', 'year', 'month'], name='reports_mon_product_5cea97_idx')],
                'unique_together': {('product', 'year', 'month')},
            },
        ),
    ]
