# Generated by Django 6.0.4 on 2026-04-25 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_number', models.CharField(max_length=50, unique=True, verbose_name='Pickup Number')),
                ('pickup_date', models.DateTimeField(db_index=True, verbose_name='Pickup Date')),
                ('destination', models.CharField(max_length=300, verbose_name='Destination')),
                ('buyer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Buyer Name')),
                ('buyer_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Buyer Phone')),
                ('status', models.CharField(choices=[('pending', 'Pending / মুলতুবি'), ('confirmed', 'Confirmed / নিশ্চিত'), ('in_transit', 'In Transit / পথে'), ('delivered', 'Delivered / বিতরণ'), ('cancelled', 'Cancelled / বাতিল')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_pickups', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickups', to='drivers.driver', verbose_name='Driver')),
            ],
            options={
                'verbose_name': 'Pickup',
                'verbose_name_plural': 'Pickups',
                'ordering': ['-pickup_date'],
            },
        ),
        migrations.CreateModel(
            name='PickupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantity')),
                ('unit_price_at_pickup', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price at Pickup')),
                ('notes', models.TextField(blank=True, default='')),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pickups.pickup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_items', to='products.product', verbose_name='Product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='pickup',
            index=models.Index(fields=['status', 'pickup_date'], name='pickups_pic_status_b8bfdf_idx'),
        ),
    ]
