# Generated by Django 6.0.4 on 2026-04-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='English name of the product', max_length=200, verbose_name='Product Name')),
                ('name_bn', models.CharField(blank=True, default='', help_text='Bengali name of the product', max_length=200, verbose_name='পণ্যের নাম')),
                ('sku', models.CharField(help_text='Stock Keeping Unit — unique product code', max_length=50, unique=True, verbose_name='SKU')),
                ('category', models.CharField(choices=[('grain', 'Grain / শস্য'), ('rice', 'Rice / চাল'), ('wheat', 'Wheat / গম'), ('pulse', 'Pulse / ডাল'), ('oilseed', 'Oilseed / তৈলবীজ'), ('spice', 'Spice / মসলা'), ('vegetable', 'Vegetable / সবজি'), ('fruit', 'Fruit / ফল'), ('fertilizer', 'Fertilizer / সার'), ('seed', 'Seed / বীজ'), ('other', 'Other / অন্যান্য')], db_index=True, default='grain', max_length=20, verbose_name='Category')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram / কেজি'), ('ton', 'Metric Ton / মেট্রিক টন'), ('quintal', 'Quintal / কুইন্টাল'), ('maund', 'Maund / মণ'), ('liter', 'Liter / লিটার'), ('piece', 'Piece / পিস'), ('bag', 'Bag / বস্তা'), ('sack', 'Sack / বস্তা')], default='kg', max_length=20, verbose_name='Unit of Measurement')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Current price per unit in BDT', max_digits=12, verbose_name='Unit Price (৳)')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, help_text='Alert threshold for low stock', max_digits=12, verbose_name='Minimum Stock Level')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('description_bn', models.TextField(blank=True, default='', verbose_name='বিবরণ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/', verbose_name='Product Image')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='products_pr_categor_226e74_idx'), models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'), models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx')],
            },
        ),
    ]
